[tool.poetry]
name = "djangoproject1"
version = "0.1.0"
description = ""
authors = ["Vladimir Rastorguev <vmrmozg138@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
django = "^6.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
